### PR TITLE
fixed requestAccessToken bug and onReceivedSslError vulnerablity

### PR DESCRIPTION
**Pull request by frostymarvelous**
Removed onReceivedSslError override due to security vulnerability.
Fixed bug where requestAccessToken failed to return or notify of an error if an exception was thrown in the AsyncTask

### CODE REVIEW

**Comment by frostymarvelous** [comment]
Fixes https://github.com/gorbin/ASNE/issues/107 
Fixes https://github.com/gorbin/ASNE/issues/69

**Comment by gianpaolodn** [comment]
Any news about this? how can I test this?

**Comment by philippeluickx** [comment]
+1
I see this got merged, but the current master is unstable, not tested nor released. Any timeline for getting a stable release?
Thanks!

**Comment by gianpaolodn** [comment]
Beginning November 25, 2016, Google Play will block publishing of any new apps or updates that contain this vulnerability. Your published APK version will remain unaffected, however any updates to the app will be rejected unless you address this vulnerability.

**Comment by pm-code** [comment]
Please suggest, what we do, should we stop using this library because my application rejected by google play.
there is no update in the library.

**Pull request merged**
